markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  auto_ids: false

gems:
  - jemoji

incremental: true

### site serving configuration ###
exclude:
  - LICENSE
  - README.md
  - CNAME
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - script/

permalink: /

# Collections
collections:
- doc

collections:
  doc:
    output: false
    permalink: :path

timezone: null
lsi: false

production_url: "http://cloudio.hevs.ch/"

### content configuration ###
title:       "cloud.iO - Scalable open source IoT solution"
keywords:    "iot, internet of things, MQTT, RabbitMQ, InfluxDB, MongoDB"
description: "Scalable open source IoT solution"
source_link: "https://github.com/cloudio-project"
favicon:     "images/favicon.ico"
touch_icon:  "images/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)

### template colors, used site-wide via css ###
colors:
  black:     '#000000'
  white:     '#fafbfd'
  gray:	     '#111111'
  navactive: '#188ac7'
